-- Create regions_countries mapping table
CREATE TABLE regions_countries (
    id VARCHAR(36) PRIMARY KEY DEFAULT NEWID(),
    region_code NVARCHAR(10) NOT NULL,
    region_name NVARCHAR(100) NOT NULL,
    country_code NVARCHAR(10) NOT NULL,
    country_name NVARCHAR(100) NOT NULL,
    is_active BIT DEFAULT 1,
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT UK_regions_countries UNIQUE (region_code, country_code)
);

-- Insert North America countries
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('NA', 'North America', 'US', 'United States'),
('NA', 'North America', 'CA', 'Canada'),
('NA', 'North America', 'MX', 'Mexico');

-- Insert EMEA countries (Europe)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('EMEA', 'Europe, Middle East, Africa', 'GB', 'United Kingdom'),
('EMEA', 'Europe, Middle East, Africa', 'DE', 'Germany'),
('EMEA', 'Europe, Middle East, Africa', 'FR', 'France'),
('EMEA', 'Europe, Middle East, Africa', 'IT', 'Italy'),
('EMEA', 'Europe, Middle East, Africa', 'ES', 'Spain'),
('EMEA', 'Europe, Middle East, Africa', 'NL', 'Netherlands'),
('EMEA', 'Europe, Middle East, Africa', 'BE', 'Belgium'),
('EMEA', 'Europe, Middle East, Africa', 'CH', 'Switzerland'),
('EMEA', 'Europe, Middle East, Africa', 'AT', 'Austria'),
('EMEA', 'Europe, Middle East, Africa', 'SE', 'Sweden'),
('EMEA', 'Europe, Middle East, Africa', 'NO', 'Norway'),
('EMEA', 'Europe, Middle East, Africa', 'DK', 'Denmark'),
('EMEA', 'Europe, Middle East, Africa', 'FI', 'Finland'),
('EMEA', 'Europe, Middle East, Africa', 'IE', 'Ireland'),
('EMEA', 'Europe, Middle East, Africa', 'PT', 'Portugal'),
('EMEA', 'Europe, Middle East, Africa', 'GR', 'Greece'),
('EMEA', 'Europe, Middle East, Africa', 'PL', 'Poland'),
('EMEA', 'Europe, Middle East, Africa', 'CZ', 'Czech Republic'),
('EMEA', 'Europe, Middle East, Africa', 'HU', 'Hungary'),
('EMEA', 'Europe, Middle East, Africa', 'SK', 'Slovakia'),
('EMEA', 'Europe, Middle East, Africa', 'SI', 'Slovenia'),
('EMEA', 'Europe, Middle East, Africa', 'HR', 'Croatia'),
('EMEA', 'Europe, Middle East, Africa', 'BG', 'Bulgaria'),
('EMEA', 'Europe, Middle East, Africa', 'RO', 'Romania'),
('EMEA', 'Europe, Middle East, Africa', 'EE', 'Estonia'),
('EMEA', 'Europe, Middle East, Africa', 'LV', 'Latvia'),
('EMEA', 'Europe, Middle East, Africa', 'LT', 'Lithuania'),
('EMEA', 'Europe, Middle East, Africa', 'CY', 'Cyprus'),
('EMEA', 'Europe, Middle East, Africa', 'MT', 'Malta'),
('EMEA', 'Europe, Middle East, Africa', 'LU', 'Luxembourg'),
('EMEA', 'Europe, Middle East, Africa', 'IS', 'Iceland'),
('EMEA', 'Europe, Middle East, Africa', 'LI', 'Liechtenstein'),
('EMEA', 'Europe, Middle East, Africa', 'MC', 'Monaco'),
('EMEA', 'Europe, Middle East, Africa', 'SM', 'San Marino'),
('EMEA', 'Europe, Middle East, Africa', 'VA', 'Vatican City'),
('EMEA', 'Europe, Middle East, Africa', 'AD', 'Andorra'),
('EMEA', 'Europe, Middle East, Africa', 'AL', 'Albania'),
('EMEA', 'Europe, Middle East, Africa', 'BA', 'Bosnia and Herzegovina'),
('EMEA', 'Europe, Middle East, Africa', 'MK', 'North Macedonia'),
('EMEA', 'Europe, Middle East, Africa', 'ME', 'Montenegro'),
('EMEA', 'Europe, Middle East, Africa', 'RS', 'Serbia'),
('EMEA', 'Europe, Middle East, Africa', 'XK', 'Kosovo'),
('EMEA', 'Europe, Middle East, Africa', 'MD', 'Moldova'),
('EMEA', 'Europe, Middle East, Africa', 'UA', 'Ukraine'),
('EMEA', 'Europe, Middle East, Africa', 'BY', 'Belarus'),
('EMEA', 'Europe, Middle East, Africa', 'RU', 'Russia');

-- Insert EMEA countries (Middle East)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('EMEA', 'Europe, Middle East, Africa', 'AE', 'United Arab Emirates'),
('EMEA', 'Europe, Middle East, Africa', 'SA', 'Saudi Arabia'),
('EMEA', 'Europe, Middle East, Africa', 'QA', 'Qatar'),
('EMEA', 'Europe, Middle East, Africa', 'KW', 'Kuwait'),
('EMEA', 'Europe, Middle East, Africa', 'BH', 'Bahrain'),
('EMEA', 'Europe, Middle East, Africa', 'OM', 'Oman'),
('EMEA', 'Europe, Middle East, Africa', 'JO', 'Jordan'),
('EMEA', 'Europe, Middle East, Africa', 'LB', 'Lebanon'),
('EMEA', 'Europe, Middle East, Africa', 'SY', 'Syria'),
('EMEA', 'Europe, Middle East, Africa', 'IQ', 'Iraq'),
('EMEA', 'Europe, Middle East, Africa', 'IR', 'Iran'),
('EMEA', 'Europe, Middle East, Africa', 'IL', 'Israel'),
('EMEA', 'Europe, Middle East, Africa', 'PS', 'Palestine'),
('EMEA', 'Europe, Middle East, Africa', 'TR', 'Turkey');

-- Insert EMEA countries (Africa)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('EMEA', 'Europe, Middle East, Africa', 'ZA', 'South Africa'),
('EMEA', 'Europe, Middle East, Africa', 'EG', 'Egypt'),
('EMEA', 'Europe, Middle East, Africa', 'NG', 'Nigeria'),
('EMEA', 'Europe, Middle East, Africa', 'KE', 'Kenya'),
('EMEA', 'Europe, Middle East, Africa', 'MA', 'Morocco'),
('EMEA', 'Europe, Middle East, Africa', 'TN', 'Tunisia'),
('EMEA', 'Europe, Middle East, Africa', 'DZ', 'Algeria'),
('EMEA', 'Europe, Middle East, Africa', 'LY', 'Libya'),
('EMEA', 'Europe, Middle East, Africa', 'SD', 'Sudan'),
('EMEA', 'Europe, Middle East, Africa', 'ET', 'Ethiopia'),
('EMEA', 'Europe, Middle East, Africa', 'UG', 'Uganda'),
('EMEA', 'Europe, Middle East, Africa', 'TZ', 'Tanzania'),
('EMEA', 'Europe, Middle East, Africa', 'GH', 'Ghana'),
('EMEA', 'Europe, Middle East, Africa', 'MZ', 'Mozambique'),
('EMEA', 'Europe, Middle East, Africa', 'MG', 'Madagascar'),
('EMEA', 'Europe, Middle East, Africa', 'CM', 'Cameroon'),
('EMEA', 'Europe, Middle East, Africa', 'CI', 'Ivory Coast'),
('EMEA', 'Europe, Middle East, Africa', 'NE', 'Niger'),
('EMEA', 'Europe, Middle East, Africa', 'BF', 'Burkina Faso'),
('EMEA', 'Europe, Middle East, Africa', 'ML', 'Mali'),
('EMEA', 'Europe, Middle East, Africa', 'MW', 'Malawi'),
('EMEA', 'Europe, Middle East, Africa', 'ZM', 'Zambia'),
('EMEA', 'Europe, Middle East, Africa', 'ZW', 'Zimbabwe'),
('EMEA', 'Europe, Middle East, Africa', 'BW', 'Botswana'),
('EMEA', 'Europe, Middle East, Africa', 'NA', 'Namibia'),
('EMEA', 'Europe, Middle East, Africa', 'SZ', 'Eswatini'),
('EMEA', 'Europe, Middle East, Africa', 'LS', 'Lesotho'),
('EMEA', 'Europe, Middle East, Africa', 'GA', 'Gabon'),
('EMEA', 'Europe, Middle East, Africa', 'GQ', 'Equatorial Guinea'),
('EMEA', 'Europe, Middle East, Africa', 'ST', 'São Tomé and Príncipe'),
('EMEA', 'Europe, Middle East, Africa', 'CV', 'Cape Verde'),
('EMEA', 'Europe, Middle East, Africa', 'GM', 'Gambia'),
('EMEA', 'Europe, Middle East, Africa', 'GW', 'Guinea-Bissau'),
('EMEA', 'Europe, Middle East, Africa', 'SL', 'Sierra Leone'),
('EMEA', 'Europe, Middle East, Africa', 'LR', 'Liberia'),
('EMEA', 'Europe, Middle East, Africa', 'GN', 'Guinea'),
('EMEA', 'Europe, Middle East, Africa', 'SN', 'Senegal'),
('EMEA', 'Europe, Middle East, Africa', 'MR', 'Mauritania'),
('EMEA', 'Europe, Middle East, Africa', 'TD', 'Chad'),
('EMEA', 'Europe, Middle East, Africa', 'CF', 'Central African Republic'),
('EMEA', 'Europe, Middle East, Africa', 'CG', 'Republic of the Congo'),
('EMEA', 'Europe, Middle East, Africa', 'CD', 'Democratic Republic of the Congo'),
('EMEA', 'Europe, Middle East, Africa', 'AO', 'Angola'),
('EMEA', 'Europe, Middle East, Africa', 'DJ', 'Djibouti'),
('EMEA', 'Europe, Middle East, Africa', 'SO', 'Somalia'),
('EMEA', 'Europe, Middle East, Africa', 'ER', 'Eritrea');

-- Insert APAC countries (Asia)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('APAC', 'Asia-Pacific', 'CN', 'China'),
('APAC', 'Asia-Pacific', 'JP', 'Japan'),
('APAC', 'Asia-Pacific', 'IN', 'India'),
('APAC', 'Asia-Pacific', 'KR', 'South Korea'),
('APAC', 'Asia-Pacific', 'TH', 'Thailand'),
('APAC', 'Asia-Pacific', 'SG', 'Singapore'),
('APAC', 'Asia-Pacific', 'MY', 'Malaysia'),
('APAC', 'Asia-Pacific', 'ID', 'Indonesia'),
('APAC', 'Asia-Pacific', 'PH', 'Philippines'),
('APAC', 'Asia-Pacific', 'VN', 'Vietnam'),
('APAC', 'Asia-Pacific', 'TW', 'Taiwan'),
('APAC', 'Asia-Pacific', 'HK', 'Hong Kong'),
('APAC', 'Asia-Pacific', 'MO', 'Macau'),
('APAC', 'Asia-Pacific', 'KH', 'Cambodia'),
('APAC', 'Asia-Pacific', 'LA', 'Laos'),
('APAC', 'Asia-Pacific', 'MM', 'Myanmar'),
('APAC', 'Asia-Pacific', 'BN', 'Brunei'),
('APAC', 'Asia-Pacific', 'TL', 'East Timor'),
('APAC', 'Asia-Pacific', 'MN', 'Mongolia'),
('APAC', 'Asia-Pacific', 'KP', 'North Korea'),
('APAC', 'Asia-Pacific', 'AF', 'Afghanistan'),
('APAC', 'Asia-Pacific', 'PK', 'Pakistan'),
('APAC', 'Asia-Pacific', 'BD', 'Bangladesh'),
('APAC', 'Asia-Pacific', 'LK', 'Sri Lanka'),
('APAC', 'Asia-Pacific', 'MV', 'Maldives'),
('APAC', 'Asia-Pacific', 'NP', 'Nepal'),
('APAC', 'Asia-Pacific', 'BT', 'Bhutan'),
('APAC', 'Asia-Pacific', 'KZ', 'Kazakhstan'),
('APAC', 'Asia-Pacific', 'KG', 'Kyrgyzstan'),
('APAC', 'Asia-Pacific', 'TJ', 'Tajikistan'),
('APAC', 'Asia-Pacific', 'TM', 'Turkmenistan'),
('APAC', 'Asia-Pacific', 'UZ', 'Uzbekistan'),
('APAC', 'Asia-Pacific', 'AM', 'Armenia'),
('APAC', 'Asia-Pacific', 'AZ', 'Azerbaijan'),
('APAC', 'Asia-Pacific', 'GE', 'Georgia');

-- Insert APAC countries (Pacific)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('APAC', 'Asia-Pacific', 'AU', 'Australia'),
('APAC', 'Asia-Pacific', 'NZ', 'New Zealand'),
('APAC', 'Asia-Pacific', 'PG', 'Papua New Guinea'),
('APAC', 'Asia-Pacific', 'FJ', 'Fiji'),
('APAC', 'Asia-Pacific', 'SB', 'Solomon Islands'),
('APAC', 'Asia-Pacific', 'VU', 'Vanuatu'),
('APAC', 'Asia-Pacific', 'NC', 'New Caledonia'),
('APAC', 'Asia-Pacific', 'PF', 'French Polynesia'),
('APAC', 'Asia-Pacific', 'WS', 'Samoa'),
('APAC', 'Asia-Pacific', 'TO', 'Tonga'),
('APAC', 'Asia-Pacific', 'KI', 'Kiribati'),
('APAC', 'Asia-Pacific', 'TV', 'Tuvalu'),
('APAC', 'Asia-Pacific', 'NR', 'Nauru'),
('APAC', 'Asia-Pacific', 'PW', 'Palau'),
('APAC', 'Asia-Pacific', 'FM', 'Micronesia'),
('APAC', 'Asia-Pacific', 'MH', 'Marshall Islands'),
('APAC', 'Asia-Pacific', 'CK', 'Cook Islands'),
('APAC', 'Asia-Pacific', 'NU', 'Niue'),
('APAC', 'Asia-Pacific', 'TK', 'Tokelau'),
('APAC', 'Asia-Pacific', 'AS', 'American Samoa'),
('APAC', 'Asia-Pacific', 'GU', 'Guam'),
('APAC', 'Asia-Pacific', 'MP', 'Northern Mariana Islands'),
('APAC', 'Asia-Pacific', 'VI', 'U.S. Virgin Islands'),
('APAC', 'Asia-Pacific', 'PR', 'Puerto Rico');

-- Insert LATAM countries (excluding Mexico which is in NA)
INSERT INTO regions_countries (region_code, region_name, country_code, country_name) VALUES
('LATAM', 'Latin America', 'BR', 'Brazil'),
('LATAM', 'Latin America', 'AR', 'Argentina'),
('LATAM', 'Latin America', 'CL', 'Chile'),
('LATAM', 'Latin America', 'CO', 'Colombia'),
('LATAM', 'Latin America', 'PE', 'Peru'),
('LATAM', 'Latin America', 'VE', 'Venezuela'),
('LATAM', 'Latin America', 'EC', 'Ecuador'),
('LATAM', 'Latin America', 'BO', 'Bolivia'),
('LATAM', 'Latin America', 'UY', 'Uruguay'),
('LATAM', 'Latin America', 'PY', 'Paraguay'),
('LATAM', 'Latin America', 'GY', 'Guyana'),
('LATAM', 'Latin America', 'SR', 'Suriname'),
('LATAM', 'Latin America', 'GF', 'French Guiana'),
('LATAM', 'Latin America', 'GT', 'Guatemala'),
('LATAM', 'Latin America', 'BZ', 'Belize'),
('LATAM', 'Latin America', 'SV', 'El Salvador'),
('LATAM', 'Latin America', 'HN', 'Honduras'),
('LATAM', 'Latin America', 'NI', 'Nicaragua'),
('LATAM', 'Latin America', 'CR', 'Costa Rica'),
('LATAM', 'Latin America', 'PA', 'Panama'),
('LATAM', 'Latin America', 'CU', 'Cuba'),
('LATAM', 'Latin America', 'JM', 'Jamaica'),
('LATAM', 'Latin America', 'HT', 'Haiti'),
('LATAM', 'Latin America', 'DO', 'Dominican Republic'),
('LATAM', 'Latin America', 'TT', 'Trinidad and Tobago'),
('LATAM', 'Latin America', 'BB', 'Barbados'),
('LATAM', 'Latin America', 'GD', 'Grenada'),
('LATAM', 'Latin America', 'VC', 'Saint Vincent and the Grenadines'),
('LATAM', 'Latin America', 'LC', 'Saint Lucia'),
('LATAM', 'Latin America', 'DM', 'Dominica'),
('LATAM', 'Latin America', 'AG', 'Antigua and Barbuda'),
('LATAM', 'Latin America', 'KN', 'Saint Kitts and Nevis'),
('LATAM', 'Latin America', 'BS', 'Bahamas'),
('LATAM', 'Latin America', 'BM', 'Bermuda');

-- Create index for better query performance
CREATE INDEX IDX_regions_countries_region ON regions_countries(region_code);
CREATE INDEX IDX_regions_countries_country ON regions_countries(country_code);
CREATE INDEX IDX_regions_countries_active ON regions_countries(is_active);